import { motion } from 'framer-motion'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { FiX } from 'react-icons/fi'
import { HiMenuAlt3, HiPlay } from 'react-icons/hi'
import { IoIosArrowRoundForward } from 'react-icons/io'
import Avatar from '../components/Avatar'
import { getFakeFaces } from '../lib'
import { useScreenSize } from '../lib/hooks'
import styles from '../styles/nft.module.css'

const links = ['marketplace', 'resources', 'community', 'FAQ']

export default function Digitally({ avatars }: { avatars: FakeFace[] }) {
   const screensize = useScreenSize()
   const isMobile = screensize.match(/xs|sm|md/i)

   return (
      <div className='bg-red-500 h-full overflow-hidden'>
         <Head>
            <title>Hapebeast demo</title>
            <meta name="description" content="Generated by elduwani" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className='noise-bg min-h-screen flex flex-col bg-gradient-to-br from-teal-100 to-blue-200 px-6'>
            {
               isMobile ? 
                  <MobileMenu logo={<Logo />} className="mb-12" /> :
                  <header className='h-20 bg-transparent flex items-center justify-between px-4 lg:px-14 mb-16 sticky top-0'>
                     <Logo />
                     <div className="flex items-center space-x-8 capitalize">
                        {
                           links.map(link => (
                              <Link href='#' key={link}>
                                 <a>{link}</a>
                              </Link>
                           ))
                        }
                     </div>
                     <div className="flex items-center space-x-4">
                        <Link href='#'>
                           <a className=''>Sign Up</a>
                        </Link>
                        <span>|</span>
                        <button className="rounded-full p-2 px-6 bg-gray-800 text-white">Connect Wallet</button>
                     </div>
                  </header>
            }
            <div className='relative flex-1 flex flex-col w-full max-w-7xl mx-auto'>
               <h3 className="flex items-end justify-between mb-2">
                  <span className='text-2xl lg:text-5xl text-gray-700 font-michroma'>RARE</span>
                  <span className='lg:text-3xl text-gray-600'>Discover, Collect &amp; Sell</span>
               </h3>
               <div className="relative w-full h-[150px] sm:h-[250px] lg:h-[320px] lg:mb-12">
                  <Image
                     src={'/nft.svg'}
                     layout='fill'
                     className='object-contain'
                     objectPosition='top left'
                  />
               </div>
               <div className="flex flex-col md:grid md:grid-cols-8 flex-1 text-gray-600 font-medium tracking-tight space-y-6 md:space-y-0">
                  <div className="col-span-2 space-y-6 z-20">
                     <p>The first NFT marketplace that enables creators to choose and embed licenses when they mint NFTs.</p>
                     <Link href='#'>
                        <a className="flex items-center space-x-8">
                           <span>Discover Now</span>
                           <span className="text-4xl w-14 h-14 rounded-full ring-2 ring-gray-600 text-gray-600 grid place-content-center">
                              <IoIosArrowRoundForward />
                           </span>
                        </a>
                     </Link>
                  </div>
                  <div className="hidden md:block col-span-2 col-start-7 lg:px-8 space-y-4 z-20">
                     <div className="flex mx-2">
                        {
                           avatars.map(av =>
                              <Avatar
                                 key={av.filename}
                                 src={av.image_url}
                                 size={isMobile ? 40 : undefined}
                                 className='bg-teal-200 md:ring-[6px] ring-4 -mx-2 ring-gray-100'
                              />
                           )
                        }
                        <Avatar
                           size={isMobile ? 40 : undefined}
                           className='bg-gray-800 text-white -mx-2 text-4xl'
                        ><HiPlay /></Avatar>
                     </div>
                     <p className='text-3xl text-gray-700'>
                        10K+ Creators
                        <span className='text-xs block mt-1'>
                           The first NFT marketplace that enables creators to choose
                        </span>
                     </p>
                  </div>
                  <div className="relative flex-1 w-full md:flex-none md:h-[70%] md:absolute md:bottom-0">
                     <Image
                        layout='fill'
                        src={'/hapebeast.png'}
                        className='z-10 object-contain'
                        objectPosition='bottom center'
                     />
                     <div className="h-[300px] w-[300px] md:h-[420px] md:w-[420px] transform -translate-y-10 md:translate-x-6 mx-auto">
                        <div className={styles.circle}>
                           <div className={'noise-bg h-full w-full bg-gray-100 rounded-full overflow-hidden z-[1]'}></div>
                        </div>
                     </div>
                  </div>
               </div>
               <div className="h-24 hidden w-full lg:flex justify-between items-center font-michroma uppercase font-extrabold text-[100px] tracking-widest">
                  <p className='bg-clip-text bg-gradient-to-r from-gray-100 to-blue-200/20 text-transparent'>rare</p>
                  <p className='bg-clip-text bg-gradient-to-r from-gray-100 to-blue-200/20 text-transparent'>nft</p>
               </div>
            </div>
         </main>
      </div>
   )
}

export const getServerSideProps: GetServerSideProps = async () => {
   const avatars = await getFakeFaces(2)
   return {
      props: {
         avatars
      },
   }
}

interface MenuProps {
   logo?: React.ReactNode
   className?: string
}
function MobileMenu(props: MenuProps) {
   const [isOpen, setIsOpen] = useState(false)
   const closeMenu = () => setIsOpen(false)
   const openMenu = () => setIsOpen(true)

   const additionalMenu = ["Sign Up"]

   return (
      <header>
         <div className={`py-4 flex items-center space-x-2 ${props.className}`}>
            <HiMenuAlt3 onClick={openMenu} className="text-2xl cursor-pointer" />
            {props.logo}
         </div>
         {
            isOpen &&
                  <motion.div
                  initial={{ opacity: 0, x: -40 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -300 }}
                  className="min-h-screen w-4/5 max-w-sm flex flex-col p-6 bg-gray-50 z-[999] fixed top-0 left-0"
               >
                  <div className="relative flex-1 flex flex-col">
                     <div
                        onClick={closeMenu}
                        className={`
                           bg-gray-100 border text-gray-600 w-8 h-8 grid place-items-center 
                           rounded-full cursor-pointer absolute right-0 top-0 z-10
                        `}
                     ><FiX className="text-lg" /></div>
                     <div className="flex-1 flex flex-col capitalize p-4">
                        {
                           links.map(route =>
                              <Link href="#" key={route}>
                                 <a className='block mb-8'>{route}</a>
                              </Link>
                           )
                        }
                        <div className="space-y-8 capitalize mt-auto">
                           {
                              additionalMenu.map(route =>
                                 <Link href="#" key={route}>
                                    <a className='block'>{route}</a>
                                 </Link>
                              )
                           }
                           <button className="w-full max-w-[200px] rounded-full p-2 px-6 bg-gray-800 text-white">Connect Wallet</button>
                        </div>
                     </div>
                  </div>
               </motion.div>
         }   
      </header>
);
}

function Logo(){
   return (
      <Link href='/'>
         <a className='text-xl md:text-2xl font-michroma text-gray-700'>Digitally</a>
      </Link>
   )
}