import Head from 'next/head'
import styles from '@styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Inspired pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Inspired pages
        </h1>

        <p className='flex flex-col space-y-2'>
          <a href="/digitally">Digitally NFT</a>
          <a href="/jadoo">Baloo</a>
        </p>
      </main>
    </div>
  )
}