import Head from 'next/head'
import styles from '@styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Inspired pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Inspired pages
        </h1>

        <p className='flex space-x-4 items-center mt-8'>
          <Link href="/beast">
            <a>Beast NFT</a>
          </Link>
          <Link href="/baloo">
            <a>Baloo</a>
          </Link>
          <Link href="/quillex">
            <a>Quillex</a>
          </Link>
        </p>
      </main>
    </div>
  )
}