import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const links = ['marketplace', 'resources', 'community', 'FAQ']


const Home: NextPage = () => {
   return (
      <div>
         <Head>
            <title>Hapebeast demo</title>
            <meta name="description" content="Generated by elduwani" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Michroma&display=swap" rel="stylesheet" />
         </Head>
         <main className='min-h-screen flex flex-col bg-[#ccc]'>
            <header className='h-20 bg-white flex items-center justify-between px-14'>
               <h1>Digitally</h1>
               <div className="flex items-center space-x-8 capitalize">
                  {
                     links.map(link => (
                        <Link href='#' key={link}>
                           <a>{link}</a>
                        </Link>
                     ))
                  }
               </div>
               <div className="flex items-center space-x-4">
                  <Link href='#'>
                     <a className=''>Sign Up</a>
                  </Link>
                  <span>|</span>
                  <button className="rounded-full p-2 px-6 bg-gray-800 text-white">Connect Wallet</button>
               </div>
            </header>
            <div className='relative flex-1 w-full max-w-7xl mx-auto ring-1 pt-20'>
               <h3 className="flex items-center justify-between mb-3">
                  <span className='text-5xl text-gray-700 font-michroma'>RARE</span>
                  <span className='text-3xl'>Discover, Collect &amp; Sell</span>
               </h3>
               {/* <div className="font-michroma text-[300px] leading-[350px] font-extrabold flex justify-between uppercase space-x-3 text-gray-800">
                  <p>N</p>
                  <p>F</p>
                  <p>T</p>
               </div> */}
               <div className="relative h-[300px]">
                  <Image
                     src={'/NFT.svg'}
                     layout='fill'
                     objectFit='cover'
                  />
               </div>
               <div className="absolute w-full h-3/4 bottom-0 ring">
                  <Image
                     src={'/hapebeast.png'}
                     layout='fill'
                     objectFit='contain'
                     className='z-10'
                  />
                  <div className="w-full h-full flex justify-center">
                     <div className="h-[500px] w-[500px] rounded-full border-[14px] transform -translate-y-10"></div>
                  </div>
               </div>
            </div>
         </main>
      </div>
   )
}

export default Home
