import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/nft.module.css'
import { IoIosArrowRoundForward } from 'react-icons/io'
import { HiPlay } from 'react-icons/hi'
import Avatar from '../components/Avatar'

const links = ['marketplace', 'resources', 'community', 'FAQ']

export default function Home() {
   return (
      <div>
         <Head>
            <title>Hapebeast demo</title>
            <meta name="description" content="Generated by elduwani" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className='min-h-screen flex flex-col bg-gradient-to-br from-teal-100 to-green-100'>
            <header className='h-20 bg-transparent flex items-center justify-between px-14 mb-16'>
               <Link href='/'>
                  <a className='text-2xl font-michroma text-gray-700'>Digitally</a>
               </Link>
               <div className="flex items-center space-x-8 capitalize">
                  {
                     links.map(link => (
                        <Link href='#' key={link}>
                           <a>{link}</a>
                        </Link>
                     ))
                  }
               </div>
               <div className="flex items-center space-x-4">
                  <Link href='#'>
                     <a className=''>Sign Up</a>
                  </Link>
                  <span>|</span>
                  <button className="rounded-full p-2 px-6 bg-gray-800 text-white">Connect Wallet</button>
               </div>
            </header>
            <div className='relative flex-1 flex flex-col w-full max-w-7xl mx-auto'>
               <h3 className="flex items-center justify-between mb-3">
                  <span className='text-5xl text-gray-700 font-michroma'>RARE</span>
                  <span className='text-3xl'>Discover, Collect &amp; Sell</span>
               </h3>
               <div className="relative h-[300px] mb-24">
                  <Image
                     src={'/NFT.svg'}
                     layout='fill'
                     objectFit='cover'
                  />
               </div>
               <div className="grid grid-cols-8 flex-1 text-gray-600 font-medium tracking-tight">
                  <div className="ring-inset col-span-2 space-y-6">
                     <p>The first NFT marketplace that enables creators to choose and embed licenses when they mint NFTs.</p>
                     <div className="flex items-center space-x-8">
                        <p>Discover Now</p>
                        <span className="text-4xl w-14 h-14 rounded-full ring-2 ring-gray-600 text-gray-600 grid place-content-center">
                           <IoIosArrowRoundForward />
                        </span>
                     </div>
                  </div>
                  <div className="ring ring-inset col-span-2 col-start-7 px-4 space-y-4">
                     <div className="flex mx-2">
                        <Avatar className='bg-teal-200 ring-[6px] -mx-2 ring-white' />
                        <Avatar className='bg-teal-200 ring-[6px] -mx-2 ring-white' />
                        <Avatar className='bg-gray-800 text-white text-4xl'>
                           <HiPlay />
                        </Avatar>
                     </div>
                     <p className='text-4xl'>
                        10K+ Creators
                        <span className='text-xs block text-gray-500 mt-1'>
                           The first NFT marketplace that enables creators to choose
                        </span>
                     </p>
                  </div>
               </div>
               <div className="absolute w-full h-3/4 bottom-0 ring-inset">
                  <Image
                     src={'/hapebeast.png'}
                     layout='fill'
                     objectFit='contain'
                     className='z-10'
                  />
                  <div className="h-[450px] w-[450px] transform -translate-y-10 translate-x-6 mx-auto">
                     <div className={styles.circle}></div>
                  </div>
               </div>
            </div>
         </main>
      </div>
   )
}
